"use client";
import Image from "next/image";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiOutlineMail } from "react-icons/ai";
import profile from "../public/Profile.png";
import filmFinder from "../public/FilmFinder.png";
import mindBody from "../public/mind-body.png";
import {
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiCsharp,
  SiReact,
  SiTailwindcss,
  SiVisualstudiocode,
} from "react-icons/si";
import { DiDotnet } from "react-icons/di";
import { BiLogoJava } from "react-icons/bi";
import { useState } from "react";
import portpic from "../public/portpic.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const darkModeStyles = {
    backgroundColor: darkMode ? "#121212" : "white",
    color: darkMode ? "white" : "black",
  };
  const projects = [
    {
      title: "Film Finder",
      description:
        "Dynamic movie search web app built with React and Vite. The App fetches movie data from the OMDB API and displays relevant details, including movie posters, release years, genres, and more.",
      image: filmFinder,
      githubLink: "https://github.com/ayacouba/FilmFinder",
      liveLink: "https://ayacouba.github.io/FilmFinder/",
    },
    {
      title: "Mind-Body",
      description:
        "Developed a responsive website to provide users with access to yoga, pilates, and meditation classes. Implemented visually appealing front-end using HTML, CSS, and Javascript.",
      image: mindBody,
      githubLink: "https://github.com/ayacouba/Mind-Body",
      liveLink: "https://ayacouba.github.io/Mind-Body/",
    },
    {
      title: "Aimade's Portfolio",
      description:
        "A portfolio website showcasing my skills, experience, and projects. Built using React, Next.js, and Tailwind CSS.",
      githubLink: "https://github.com/ayacouba/aimade-portfolio",
      image: portpic,
      liveLink: "",
    },
  ];
  const languagesTechnologies = [
    { icon: SiJavascript, name: "JavaScript" },
    { icon: BiLogoJava, name: "Java" },
    { icon: SiHtml5, name: "HTML" },
    { icon: SiCss3, name: "CSS" },
    { icon: SiCsharp, name: "C#" },
    { icon: SiReact, name: "React" },
    { icon: SiTailwindcss, name: "Tailwind" },
    { icon: SiVisualstudiocode, name: "VS Code" },
    { icon: DiDotnet, name: "Dotnet" },
  ];
  return (
    <div style={darkModeStyles}>
      <Head>
        <title>Aimade Portfolio</title>
        <meta name="description" content="Generated by emmz"></meta>
        <link rel="icon" href="./public" />
      </Head>

      <main className={darkMode ? "bg-gray-900 text-white" : "bg-white"}>
        <section className="  min-h-screen" style={darkModeStyles}>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Aimade Yacouba</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1rqmXGU7DQHmS3Y6xCI3pInh0rxySBEtQ/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Aimade Yacouba
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Aspiring Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl">
              As a college senior majoring in Computer Science, I am passionate
              about leveraging technology to solve real-world problems. With a
              focus on software development, I have honed my skills in various
              languages and frameworks. Currently, I am working part-time as a
              developer, specializing in .NET, where I have the opportunity to
              apply and expand my technical skills. I'm eager to take the next
              step in my career and contribute my knowledge and creativity to
              innovative projects.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/aimade-yacouba-673a1a200/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/ayacouba" target="_blank">
              <AiFillGithub />
            </a>
            <a href="mailto:aimadeyacouba92@gmail.com">
              <AiOutlineMail />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={profile}
              alt="Aimade Pic"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section>
          <h2 className="text-3xl font-medium text-center py-10 text-teal-600 underline">
            Projects
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2  p-10 justify-items-center">
            {projects.map((project, index) => (
              <div
                key={index}
                className="rounded-md shadow-lg overflow-hidden max-w-lg"
              >
                <a href={project.liveLink} target="_blank">
                  <Image
                    src={project.image}
                    alt={project.title}
                    layout="responsive"
                    objectFit="cover"
                    className="rounded-md"
                  />
                </a>
                <div className="p-4 bg-white">
                  <h3 className="text-xl font-medium mt-3">{project.title}</h3>
                  <p className="text-md py-1 text-gray-700">
                    {project.description}
                  </p>
                  <div className="flex justify-end">
                    <a
                      href={project.githubLink}
                      className="text-teal-600 hover:text-teal-800"
                    >
                      GitHub
                    </a>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="p-10">
          <h2 className="text-3xl font-medium text-center py-5 text-teal-600 underline">
            Languages & Technologies
          </h2>
          <div className="flex flex-wrap justify-center gap-8 text-center">
            {languagesTechnologies.map((item, index) => (
              <div key={index}>
                <item.icon className="text-4xl mx-auto mb-2" />
                <p className="text-lg font-medium">{item.name}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
